### ISSUE TITLE
Can you explain NewSpace function parameters a bit more?

### ISSUE THREAD

**Issue by piotrowski** [zergon321/cirno#2]
Hello! Firstly I would like to say that, the library is amazing, and it is documented very well. However I found one place a bit complicated for me:

```
func NewSpace(subdivisionFactor, shapesInArea int, width, height float64, min, max Vector, useTags bool) (*Space, error)
```
What for are those variables?
* subdivisionFactor
* shapesInArea
* width
* height

**Comment by zergon321** [comment]
Hello! Thank you for using the library.

The collision space is restricted by a rectangle with `width` and `height` passed as arguments in the `NewSpace` function.

`subdivisionFactor` is the max depth of the underlying quadtree minus 1, so it's the max level of the node in the quadtree (levels are in the range of [0; subdivisionFactor]).

`shapesInArea` is the max number of shapes a single quadtree node can take.

So initially there's a quadtree with only one root node which has level 0. When its shape count reaches the number of `shapesInArea`, the next insertion will make the node split into 4 subnodes and redistribute all the shapes into them. These subnodes are all of level 1, because the parent was 0. If the limit of one of these subnodes is exceeded, it splits into 4 subnodes of level 2, and so on, that's how quadtrees work.

If the node reaches the level of `subdivisionFactor`, it cannot split anymore and will accept shapes regardless of its shape count and `shapesInArea` limit.

So what does this mean for the user of the library? Well, he should pick the values that will be efficient for his current situation. You can take a look at the `examples` folder with some demos with prepared values for `subdivisionFactor` and `shapesInArea`.

And please be careful, the work on the project is still in progress, the API might change anytime, and I still haven't yet fixed the normals for `rectangle-rectangle` and `rectangle-line` cases.

**Comment by apiotrowski312** [comment]
No worries. I am just playing with it and creating simple game for learning purposes only.

Thanks! I think I have to dive deep into quadtree to understand it better.
